makefile_build_task:
  env:
    CIRRUS_CLONE_DEPTH: 1
  container:
    matrix:
      image: gcc:5
      image: gcc:6
      image: gcc:7
      image: gcc:8
    cpu: 3
    memory: 1G
  build_script: make clean && make -j3
  install_script: make install && make clean
  ## now try the built+installed sjasmplus with some tests and examples
  # this is not separate task, because that would need again build
  # of sjasmplus in new container instance, so just do everything in one task
  assemble_tests_script: ContinuousIntegration/test_folder_tests.sh
  assemble_examples_script: ContinuousIntegration/test_folder_examples.sh

pipe:
  name: coveralls.io coverage report
  depends_on: makefile_build
  env:
    CIRRUS_CLONE_DEPTH: 1
    # coveralls plugin variables (access token + job ID)
    COVERALLS_REPO_TOKEN: ENCRYPTED[84a87f67d61b85be01b63f6aec68a5fb644f02b2febff3d83a9af810f52a8e3023486286e1ac76c527fad3dc06fbc692]
    TRAVIS_JOB_ID: ${CIRRUS_BUILD_ID}
    # makefile variables affecting build options
    DEBUG: 1
    COVERALLS_SERVICE: 1
  resources:
    cpu: 3
    memory: 1G
  steps:
    - image: gcc:7
      generate_gcov_script: make clean && make -j3 coverage
    - image: python:3.7
      install_coveralls_plugin_script: pip install cpp-coveralls
      # "-n" as the *.gcov files are already generated in the project root from previous step
      upload_gcov_data_script: coveralls -n -y ContinuousIntegration/coveralls.yml
