#task:
  #name: FreeBSD clang-6 build
  #env:
    #CIRRUS_CLONE_DEPTH: 1
  #freebsd_instance:
    #image: freebsd-12-0-release-amd64
    #cpu: 4
    #memory: 4G
  #sw_install_script: pkg lock -y pkg && pkg install -y git-lite gmake bash
  #submodules_script:
    #- git submodule init
    #- git submodule update
  #build_script: gmake clean && gmake -j4 CC=cc CXX=c++
  #test_script: gmake clean && gmake -j4 CC=cc CXX=c++ tests

task:
  name: MacOS default CC build
  env:
    CIRRUS_CLONE_DEPTH: 1
  osx_instance:
    image: mojave-base
  #sw_versions2_script:
    #- git --version || echo "no git"
    #- bash --version || echo "no bash"
    #- make --version || echo "no make"
    #- cc --version || echo "no cc"
    #- c++ --version || echo "no c++"
  submodules_script:
    - git submodule init
    - git submodule update
  build_script:
    - date
    - make clean && make -j4 CC=cc CXX=c++
  test_script: make clean && make -j4 CC=cc CXX=c++ tests
